// src/app/components/bidding-form/bidding-form.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { BiddingService } from '../../services/bidding.service';

@Component({
  selector: 'app-bidding-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <div class="container mx-auto p-4">
      <h2 class="text-2xl font-bold mb-4">{{ isEditing ? 'Editar' : 'Nova' }} Licitação</h2>
      
      <form [formGroup]="form" (ngSubmit)="onSubmit()" class="max-w-lg">
        <div class="mb-4">
          <label class="block mb-2">Número</label>
          <input type="text" formControlName="number" class="w-full p-2 border rounded">
        </div>

        <div class="mb-4">
          <label class="block mb-2">Ano</label>
          <input type="number" formControlName="year" class="w-full p-2 border rounded">
        </div>

        <div class="mb-4">
          <label class="block mb-2">Título</label>
          <input type="text" formControlName="title" class="w-full p-2 border rounded">
        </div>

        <div class="mb-4">
          <label class="block mb-2">Descrição</label>
          <textarea formControlName="description" class="w-full p-2 border rounded" rows="4"></textarea>
        </div>

        <div class="mb-4">
          <label class="block mb-2">Data de Abertura</label>
          <input type="datetime-local" formControlName="openingDate" class="w-full p-2 border rounded">
        </div>

        <div class="mb-4">
          <label class="block mb-2">Data de Encerramento</label>
          <input type="datetime-local" formControlName="closingDate" class="w-full p-2 border rounded">
        </div>

        <div class="mb-4">
          <label class="block mb-2">Valor Estimado</label>
          <input type="number" formControlName="estimatedValue" class="w-full p-2 border rounded">
        </div>

        <div class="mb-4">
          <label class="block mb-2">Tipo</label>
          <select formControlName="type" class="w-full p-2 border rounded">
            <option value="pregao">Pregão</option>
            <option value="tomada_preco">Tomada de Preço</option>
            <option value="concorrencia">Concorrência</option>
            <option value="convite">Convite</option>
          </select>
        </div>

        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded" [disabled]="form.invalid">
          Salvar
        </button>
      </form>
    </div>
  `
})
export class BiddingFormComponent implements OnInit {
  form: FormGroup;
  isEditing = false;

  constructor(
    private fb: FormBuilder,
    private biddingService: BiddingService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.form = this.fb.group({
      number: ['', Validators.required],
      year: [new Date().getFullYear(), Validators.required],
      title: ['', Validators.required],
      description: ['', Validators.required],
      openingDate: ['', Validators.required],
      closingDate: ['', Validators.required],
      estimatedValue: [0, Validators.required],
      type: ['pregao', Validators.required],
      status: ['draft'],
      documents: [[]]
    });
  }

  ngOnInit() {
    const id = this.route.snapshot.params['id'];
    if (id) {
      this.isEditing = true;
      this.biddingService.getBiddingById(+id).subscribe(bidding => {
        if (bidding) {
          this.form.patchValue(bidding);
        }
      });
    }
  }

  onSubmit() {
    if (this.form.valid) {
      const bidding = this.form.value;
      
      if (this.isEditing) {
        const id = this.route.snapshot.params['id'];
        this.biddingService.updateBidding(id, bidding).subscribe(() => {
          this.router.navigate(['/licitacoes']);
        });
      } else {
        this.biddingService.createBidding(bidding).subscribe(() => {
          this.router.navigate(['/licitacoes']);
        });
      }
    }
  }
}

// src/components/BiddingForm.vue
<template>
  <div class="container mx-auto p-4">
    <h2 class="text-2xl font-bold mb-6">
      {{ isEditing ? 'Editar' : 'Nova' }} Licitação
    </h2>

    <form @submit.prevent="onSubmit" class="max-w-lg">
      <div class="space-y-4">
        <div>
          <label class="block text-sm font-medium text-gray-700">Número</label>
          <input
            v-model="form.number"
            type="text"
            required
            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700">Ano</label>
          <input
            v-model="form.year"
            type="number"
            required
            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700">Título</label>
          <input
            v-model="form.title"
            type="text"
            required
            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700">Descrição</label>
          <textarea
            v-model="form.description"
            rows="4"
            required
            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
          ></textarea>
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700">
            Data de Abertura
          </label>
          <input
            v-model="form.openingDate"
            type="datetime-local"
            required
            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700">
            Data de Encerramento
          </label>
          <input
            v-model="form.closingDate"
            type="datetime-local"
            required
            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700">
            Valor Estimado
          </label>
          <input
            v-model="form.estimatedValue"
            type="number"
            required
            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700">Tipo</label>
          <select
            v-model="form.type"
            required
            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
          >
            <option value="pregao">Pregão</option>
            <option value="tomada_preco">Tomada de Preço</option>
            <option value="concorrencia">Concorrência</option>
            <option value="convite">Convite</option>
          </select>
        </div>
      </div>

      <div class="mt-6">
        <button
          type="submit"
          class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
        >
          Salvar
        </button>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useBiddingStore } from '../stores/bidding';
import type { Bidding } from '../types/bidding';

const route = useRoute();
const router = useRouter();
const biddingStore = useBiddingStore();

const isEditing = ref(false);
const form = ref({
  number: '',
  year: new Date().getFullYear(),
  title: '',
  description: '',
  openingDate: '',
  closingDate: '',
  estimatedValue: 0,
  type: 'pregao' as Bidding['type'],
  status: 'draft' as Bidding['status'],
  documents: [] as string[]
});

onMounted(() => {
  const id = route.params.id;
  if (id) {
    isEditing.value = true;
    const bidding = biddingStore.getBidding(Number(id));
    if (bidding) {
      form.value = { ...bidding };
    }
  }
});

const onSubmit = () => {
  if (isEditing.value) {
    biddingStore.updateBidding(Number(route.params.id), form.value);
  } else {
    biddingStore.addBidding(form.value);
  }
  router.push('/licitacoes');
};
</script>
